version: '3.5'
services:

  degressly-core:
    image: degressly-core
    build:
      context: ../degressly-core
      dockerfile: ../degressly-core/Dockerfile
    container_name: degressly-core
    networks:
      - degressly_demo_network
    depends_on:
      - degressly-demo-primary
      - degressly-demo-secondary
      - degressly-demo-candidate
      - kafka
    ports:
      - "8000:8000"
    env_file:
      - .env

# Comparator config
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: degressly-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22182:2181"
    networks:
      - degressly_demo_network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    container_name: kafka
    networks:
      - degressly_demo_network
    ports:
      - "29092:29092"

    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: degressly-zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    restart: unless-stopped

  degressly-comparator:
    image: degressly-comparator
    build:
      context: ../degressly-comparator
      dockerfile: ../degressly-comparator/Dockerfile
    container_name: degressly-comparator
    networks:
      - degressly_demo_network
    env_file:
      - .env
    depends_on:
      - kafka
      - mongo
  
  mongo:
    image: mongo
    container_name: "degressly-mongo"
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - degressly_demo_network
# Comparator config complete

  degressly-downstream:
    image: degressly-downstream
    build:
      context: ../degressly-downstream
      dockerfile: ../degressly-downstream/Dockerfile
    container_name: degressly-downstream
    networks:
      - degressly_demo_network
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - kafka

  degressly-demo-primary:
    image: degressly-demo
    container_name: "degressly-demo-primary"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_PROXY: http://degressly-downstream:8080
      HTTPS_PROXY: http://degressly-downstream:8080
      PORT: 8080
    networks:
      - degressly_demo_network
    depends_on:
      - degressly-downstream
  
  degressly-demo-secondary:
    image: degressly-demo
    container_name: "degressly-demo-secondary"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_PROXY: http://degressly-downstream:8080
      HTTPS_PROXY: http://degressly-downstream:8080
      PORT: 8081
    networks:
      - degressly_demo_network
    depends_on:
      - degressly-downstream
  
  degressly-demo-candidate:
    image: degressly-demo
    container_name: "degressly-demo-candidate"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_PROXY: http://degressly-downstream:8080
      HTTPS_PROXY: http://degressly-downstream:8080
      PORT: 8082
    networks:
      - degressly_demo_network
    depends_on:
      - degressly-downstream

networks:
  degressly_demo_network:
    name: degressly_example_network